export const mockCarts = [
  {
    id: "CART-001",
    customer: "Sherif Mansour",
    email: "sherif.mansour1@example.com",
    status: "active",
    items: [
      { name: "Monitor Arm", quantity: 3, price: 220.0 },
      { name: "Smart Watch", quantity: 1, price: 899.0 },
      { name: "Ring Light", quantity: 3, price: 95.0 },
      { name: "Phone Case", quantity: 1, price: 25.0 },
    ],
    coupon: "OFF50",
    updatedAt: "9 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 225,
  },
  {
    id: "CART-002",
    customer: "Sara Younis",
    email: "sara.younis2@example.com",
    status: "active",
    items: [
      { name: "Monitor Arm", quantity: 2, price: 220.0 },
    ],
    coupon: null,
    updatedAt: "19 hours ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 19,
  },
  {
    id: "CART-003",
    customer: "Menna Doe",
    email: "menna.doe3@example.com",
    status: "abandoned",
    items: [
      { name: "Monitor Arm", quantity: 2, price: 220.0 },
      { name: "Portable SSD 1TB", quantity: 1, price: 550.0 },
      { name: "Power Bank 20000mAh", quantity: 2, price: 149.99 },
    ],
    coupon: null,
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 123,
  },
  {
    id: "CART-004",
    customer: "Amr Gaber",
    email: "amr.gaber4@example.com",
    status: "abandoned",
    items: [
      { name: "Webcam 1080p", quantity: 3, price: 129.0 },
      { name: "Bluetooth Speaker", quantity: 1, price: 199.5 },
      { name: "Wireless Headphones", quantity: 1, price: 249.99 },
      { name: "Ring Light", quantity: 2, price: 95.0 },
    ],
    coupon: null,
    updatedAt: "4 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 110,
  },
  {
    id: "CART-005",
    customer: "Wael Nabil",
    email: "wael.nabil5@example.com",
    status: "active",
    items: [
      { name: "Power Bank 20000mAh", quantity: 2, price: 149.99 },
      { name: "Mechanical Keyboard", quantity: 2, price: 349.0 },
      { name: "Portable SSD 1TB", quantity: 3, price: 550.0 },
      { name: "Laptop Stand", quantity: 3, price: 89.0 },
    ],
    coupon: null,
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 169,
  },
  {
    id: "CART-006",
    customer: "Sara Khaled",
    email: "sara.khaled6@example.com",
    status: "abandoned",
    items: [
      { name: "Laptop Stand", quantity: 3, price: 89.0 },
      { name: "Mechanical Keyboard", quantity: 3, price: 349.0 },
    ],
    coupon: null,
    updatedAt: "9 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 223,
  },
  {
    id: "CART-007",
    customer: "Mahmoud Doe",
    email: "mahmoud.doe7@example.com",
    status: "completed",
    items: [
      { name: "USB-C Cable", quantity: 2, price: 15.99 },
      { name: "Noise Cancelling Earbuds", quantity: 3, price: 399.0 },
      { name: "Desk Lamp", quantity: 3, price: 65.0 },
      { name: "Mechanical Keyboard", quantity: 1, price: 349.0 },
    ],
    coupon: null,
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 179,
  },
  {
    id: "CART-008",
    customer: "Omar Hegazy",
    email: "omar.hegazy8@example.com",
    status: "abandoned",
    items: [
      { name: "Mouse Pad", quantity: 3, price: 45.0 },
      { name: "Desk Lamp", quantity: 1, price: 65.0 },
      { name: "Ring Light", quantity: 2, price: 95.0 },
      { name: "Monitor Arm", quantity: 1, price: 220.0 },
    ],
    coupon: null,
    updatedAt: "4 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 113,
  },
  {
    id: "CART-009",
    customer: "Nada Ashraf",
    email: "nada.ashraf9@example.com",
    status: "abandoned",
    items: [
      { name: "Bluetooth Speaker", quantity: 2, price: 199.5 },
      { name: "Monitor Arm", quantity: 1, price: 220.0 },
      { name: "Smart Watch", quantity: 2, price: 899.0 },
      { name: "Ring Light", quantity: 3, price: 95.0 },
    ],
    coupon: null,
    updatedAt: "3 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 87,
  },
  {
    id: "CART-010",
    customer: "Mahmoud Hassan",
    email: "mahmoud.hassan10@example.com",
    status: "active",
    items: [
      { name: "Webcam 1080p", quantity: 1, price: 129.0 },
      { name: "Mouse Pad", quantity: 2, price: 45.0 },
      { name: "Wireless Headphones", quantity: 1, price: 249.99 },
    ],
    coupon: null,
    updatedAt: "4 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 102,
  },
  {
    id: "CART-011",
    customer: "Adham Hegazy",
    email: "adham.hegazy11@example.com",
    status: "payment_pending",
    items: [
      { name: "Desk Lamp", quantity: 1, price: 65.0 },
    ],
    coupon: null,
    updatedAt: "1 day ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 43,
  },
  {
    id: "CART-012",
    customer: "Aya Mostafa",
    email: "aya.mostafa12@example.com",
    status: "abandoned",
    items: [
      { name: "Gaming Mouse", quantity: 1, price: 179.0 },
      { name: "Monitor Arm", quantity: 3, price: 220.0 },
      { name: "Mouse Pad", quantity: 1, price: 45.0 },
    ],
    coupon: null,
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 122,
  },
  {
    id: "CART-013",
    customer: "Youssef Younis",
    email: "youssef.younis13@example.com",
    status: "cancelled",
    items: [
      { name: "Mouse Pad", quantity: 2, price: 45.0 },
      { name: "Wireless Headphones", quantity: 3, price: 249.99 },
    ],
    coupon: null,
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 136,
  },
  {
    id: "CART-014",
    customer: "Sherif Wahba",
    email: "sherif.wahba14@example.com",
    status: "completed",
    items: [
      { name: "USB-C Cable", quantity: 1, price: 15.99 },
    ],
    coupon: null,
    updatedAt: "8 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 213,
  },
  {
    id: "CART-015",
    customer: "Tarek Khaled",
    email: "tarek.khaled15@example.com",
    status: "active",
    items: [
      { name: "Laptop Stand", quantity: 3, price: 89.0 },
    ],
    coupon: null,
    updatedAt: "3 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 91,
  },
  {
    id: "CART-016",
    customer: "John Ali",
    email: "john.ali16@example.com",
    status: "active",
    items: [
      { name: "Mouse Pad", quantity: 1, price: 45.0 },
      { name: "Power Bank 20000mAh", quantity: 2, price: 149.99 },
      { name: "Phone Case", quantity: 2, price: 25.0 },
    ],
    coupon: null,
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 189,
  },
  {
    id: "CART-017",
    customer: "Khaled Zidan",
    email: "khaled.zidan17@example.com",
    status: "completed",
    items: [
      { name: "Desk Lamp", quantity: 3, price: 65.0 },
    ],
    coupon: null,
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 172,
  },
  {
    id: "CART-018",
    customer: "Farida Mansour",
    email: "farida.mansour18@example.com",
    status: "payment_pending",
    items: [
      { name: "Phone Case", quantity: 2, price: 25.0 },
      { name: "Smart Watch", quantity: 1, price: 899.0 },
      { name: "Noise Cancelling Earbuds", quantity: 2, price: 399.0 },
      { name: "Laptop Stand", quantity: 1, price: 89.0 },
    ],
    coupon: "WELCOME15",
    updatedAt: "2 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 49,
  },
  {
    id: "CART-019",
    customer: "Heba Gaber",
    email: "heba.gaber19@example.com",
    status: "active",
    items: [
      { name: "Smart Watch", quantity: 3, price: 899.0 },
      { name: "USB-C Cable", quantity: 3, price: 15.99 },
    ],
    coupon: null,
    updatedAt: "3 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 92,
  },
  {
    id: "CART-020",
    customer: "Salma Mansour",
    email: "salma.mansour20@example.com",
    status: "abandoned",
    items: [
      { name: "Ring Light", quantity: 3, price: 95.0 },
      { name: "Gaming Mouse", quantity: 3, price: 179.0 },
      { name: "Laptop Stand", quantity: 3, price: 89.0 },
    ],
    coupon: null,
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 176,
  },
  {
    id: "CART-021",
    customer: "Salma Fathy",
    email: "salma.fathy21@example.com",
    status: "abandoned",
    items: [
      { name: "Gaming Mouse", quantity: 3, price: 179.0 },
      { name: "Smart Watch", quantity: 2, price: 899.0 },
      { name: "Wireless Headphones", quantity: 1, price: 249.99 },
      { name: "Noise Cancelling Earbuds", quantity: 2, price: 399.0 },
    ],
    coupon: "WELCOME15",
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 124,
  },
  {
    id: "CART-022",
    customer: "Laila Yousry",
    email: "laila.yousry22@example.com",
    status: "cancelled",
    items: [
      { name: "Portable SSD 1TB", quantity: 2, price: 550.0 },
      { name: "Webcam 1080p", quantity: 2, price: 129.0 },
      { name: "Bluetooth Speaker", quantity: 3, price: 199.5 },
      { name: "Monitor Arm", quantity: 2, price: 220.0 },
    ],
    coupon: null,
    updatedAt: "4 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 119,
  },
  {
    id: "CART-023",
    customer: "Hana Gaber",
    email: "hana.gaber23@example.com",
    status: "completed",
    items: [
      { name: "Phone Case", quantity: 3, price: 25.0 },
      { name: "Wireless Headphones", quantity: 3, price: 249.99 },
      { name: "Bluetooth Speaker", quantity: 3, price: 199.5 },
    ],
    coupon: "WELCOME15",
    updatedAt: "7 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 181,
  },
  {
    id: "CART-024",
    customer: "Adham Saeed",
    email: "adham.saeed24@example.com",
    status: "completed",
    items: [
      { name: "Gaming Mouse", quantity: 1, price: 179.0 },
      { name: "Laptop Stand", quantity: 3, price: 89.0 },
      { name: "Mouse Pad", quantity: 1, price: 45.0 },
      { name: "Smart Watch", quantity: 1, price: 899.0 },
    ],
    coupon: "WELCOME15",
    updatedAt: "6 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 146,
  },
  {
    id: "CART-025",
    customer: "Hana Saeed",
    email: "hana.saeed25@example.com",
    status: "abandoned",
    items: [
      { name: "Desk Lamp", quantity: 2, price: 65.0 },
      { name: "Mouse Pad", quantity: 1, price: 45.0 },
    ],
    coupon: "WELCOME15",
    updatedAt: "9 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 235,
  },
  {
    id: "CART-026",
    customer: "Omar Lotfy",
    email: "omar.lotfy26@example.com",
    status: "cancelled",
    items: [
      { name: "Power Bank 20000mAh", quantity: 2, price: 149.99 },
      { name: "Noise Cancelling Earbuds", quantity: 3, price: 399.0 },
      { name: "Desk Lamp", quantity: 1, price: 65.0 },
    ],
    coupon: null,
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 127,
  },
  {
    id: "CART-027",
    customer: "Reem Rizk",
    email: "reem.rizk27@example.com",
    status: "active",
    items: [
      { name: "Gaming Mouse", quantity: 3, price: 179.0 },
      { name: "Mouse Pad", quantity: 2, price: 45.0 },
      { name: "Desk Lamp", quantity: 2, price: 65.0 },
      { name: "Smart Watch", quantity: 2, price: 899.0 },
    ],
    coupon: "OFF50",
    updatedAt: "5 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 121,
  },
  {
    id: "CART-028",
    customer: "Heba Gaber",
    email: "heba.gaber28@example.com",
    status: "completed",
    items: [
      { name: "Phone Case", quantity: 1, price: 25.0 },
      { name: "Ring Light", quantity: 2, price: 95.0 },
      { name: "USB-C Cable", quantity: 2, price: 15.99 },
    ],
    coupon: "SAVE10",
    updatedAt: "9 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 222,
  },
  {
    id: "CART-029",
    customer: "Nada Sabry",
    email: "nada.sabry29@example.com",
    status: "payment_pending",
    items: [
      { name: "USB-C Cable", quantity: 1, price: 15.99 },
    ],
    coupon: "SAVE10",
    updatedAt: "8 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 215,
  },
  {
    id: "CART-030",
    customer: "Salma Farouk",
    email: "salma.farouk30@example.com",
    status: "payment_pending",
    items: [
      { name: "Phone Case", quantity: 2, price: 25.0 },
    ],
    coupon: null,
    updatedAt: "2 days ago",
    updatedAtTimestamp: Date.now() - 1000 * 60 * 60 * 51,
  },
];